# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'


        }
                   #Uploading and scanning the artifact zip in HPFortify

                   $exe = "c:\FoDUploader.exe"
                   &$exe --source "D:\fortify\artifacts\$APIversion-$APIname.zip" --apiToken "*******" --                                      apiTokenSecret "*************" --uploadURL "https://api.hpfod.com/bsi2.aspx?                                                tid=828&tc=sm&pv=$releaseId&payloadType=ANALYSIS_PAYLOAD&astid=170&ts=.NET&ll=4.5" --                      automatedAudit "True" --expressScan "True" --includeAllFiles "True" --debug "True"

                  }
                  }
                  }